_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
langcode: en-gb
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: true
  contact_message_personal_form: true
  node_article_form: false
  node_front_form: false
  node_garden_form: false
  node_landing_page_form: false
  node_page_form: false
  node_press_form: false
  node_staff_form: false
  node_testimonial_form: false
  node_webform_form: false
